services:

  minio:
    container_name: minio
    restart: unless-stopped
    image: minio/minio
    command: server /data --console-address "0.0.0.0:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  minio-data:
