services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - docker-network
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  docker-network:
    driver: bridge

volumes:
  postgres-data: